version: "2"
services:
  backend:
    build: server
    ports: 
      - 3001:3000
    container_name: backend-container
    restart: always

  database:
    build: database
    container_name: database-container
    restart: always

  frontend:
    build: app
    ports: 
      - 8080:8080
    container_name: frontend-container
    restart: always